spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luzflucky/server-config
          username: 569350384@qq.com
          password: a18861856674..
          default-label: master
          search-paths: /**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
